function retour_chapitres(le_certif)
{
	var chaine_chapitres='';

	switch(le_certif)
	{
		case'1':
			chaine_chapitres='4Cardiologie : Electrocardiogramme|5Cardiologie : Les explorations en cardiologie|6Cardiologie : Le rétrécissement mitral|7Cardiologie : L insuffisance mitrale|8Cardiologie : Le rétrécissement aortique|9Cardiologie : L insuffisance aortique|10Cardiologie : L’endocardite infectieuse|11Cardiologie : L’hypertension artérielle|12Cardiologie : L’œdème aigu du poumon|13Cardiologie : L’insuffisance cardiaque|14Cardiologie : L’angor stable|15Cardiologie : SCA sans sus décalage de ST|16Cardiologie : SCA avec sus décalage de ST|19Cardiologie : La thrombose veineuse profonde des membres|20Cardiologie : L’embolie pulmonaire|21Cardiologie : Les péricardites|22Cardiologie : Les cardiopathies congénitales non cyanogènes|23Cardiologie : Les cardiopathies congénitales cyanogènes|24Cardiologie : Les troubles de la conduction|25Cardiologie : Trouble du rythme|26Cardiologie : Les cardiomyopathies|27Chirurgie Cardiaque : Anévrysme artériel des membres|28Chirurgie Cardiaque : Varices de membres inférieurs|29Chirurgie Cardiaque : Artérite chronique des membres inférieurs|30Chirurgie Cardiaque : Dissection aigue de l’aorte|31Chirurgie Cardiaque : Ischémie aigue des membres|32Chirurgie Cardiaque : Généralités sur la chirurgie cardiaque|33Anatomie pathologique : Athérosclérose|34Anatomie pathologique : Cardiopathies ischémiques|35Anatomie pathologique : Lésions inflammatoires du cœur|36Pharmacologie: Médicaments du SNA|37Pharmacologie: Les anti-hypertenseurs|38Pharmacologie: Médicaments de l’insuffisance cardiaque|39Pharmacologie: Médicaments de l’insuffisance coronaire|40Pharmacologie: Les dépresseurs de l’hémostase|41Pharmacologie: Les anti-arythmiques|42Imagerie : Imagerie cardiaque|43Imagerie : Imagerie vasculaire';
			break;
		case'2':
			chaine_chapitres='44Pneumologie : Explorations en pneumologie|45Pneumologie : Méthodes de diagnostic et d’exploration en allergie respiratoire|46Pneumologie : Primo-infection tuberculeuse|47Pneumologie : Tuberculose pulmonaire commune|48Pneumologie : Traitement de la tuberculose|49Pneumologie : Infections respiratoires basses|50Pneumologie : Asthme|51Pneumologie : Traitement de l’asthme|52Pneumologie : Bronchopneumopathies Chroniques Obstructives|53Pneumologie : Syndrome d’apnée obstructive du sommeil|54Pneumologie : Dilatation de bronches|55Pneumologie : Pneumopathies infiltrantes diffuses|56Pneumologie : Cancer broncho-pulmonaire primitif : clinique|57Pneumologie : Cancer broncho-pulmonaire primitif : prise en charge|58Pneumologie : Syndromes médiastinaux|59Pneumologie : Insuffisances respiratoires chroniques|60Pneumologie : Insuffisances respiratoires aigues|61Pneumologie : Opacité ronde intra-pulmonaire : Approche clinique|62Pneumologie : Hémoptysie|63Pneumologie : Pathologies liées au tabac|64Pneumologie : Pleurésie à liquide clair|65Pneumologie : Pleurésie purulente|66Pneumologie : Pneumothorax spontané|67Chirurgie Thoracique : Le drainage thoracique|68Chirurgie Thoracique : Traumatismes du thorax|69Chirurgie Thoracique : Kyste hydatique du poumon|70Pharmacologie : Les antituberculeux|71Pharmacologie : Les médicaments de l’asthme|72Pharmacologie : Les antitussifs et modificateurs des sécrétions bronchiques|73A. Pathologique : Lésions tuberculeuses|74A. Pathologique : Pathologie pulmonaire inflammatoire et dystrophique|75A. Pathologique : Apport de la cytologie en pathologie pulmonaire|76Anatomie pathologique : Les tumeurs broncho-pulmonaires|77Imagerie : Syndrome bronchique et troubles ventilatoires|78Imagerie : Syndrome alvéolaire et interstitiel|79Imagerie : Syndrome pleural et pariétal|80Imagerie : Diagnostic d’une opacité ronde pulmonaire|81Imagerie : Syndrome médiastinaux|82Bactériologique : Les mycobactéries|83Bactériologique : Ecologie bactérienne des IRB';
			break;
		case'7':
			chaine_chapitres='84Infection à paramyxovirus|85Infection à adénovirus, entérovirus|86Diagnostic biologique des déficits immunitaires|87Urgences métaboliques|88Particularités de l\'hypertension artérielle chez l’enfant|89Méningites|90Bronchopneumopathies récidivantes|91Infections respiratoires aigues basses|92Infections respiratoires aigües hautes|93Les vomissements de l\'enfant|94Diabète sucré|95Hypothyroïdie|96Retard de croissance|97Intoxications aigues|98Alimentation du nourrisson|99Détresses vitales: Les états de choc|100Détresses vitales: Détresse respiratoire et arrêt cardiaque|101Anomalies pubertaires|102Pb génitaux du nouveau-né, nourrisson, enfant|103Infections urinaires|104Convulsion – Epilepsie|105Leishmaniose viscérale|106Retard psychomoteur|107Diarrhée chronique|108Malnutrition protéinoénergétique|109Diagnostic d\'un purpura chez l\'enfant|110Hypotonie chronique du nourrisson|111Syndrome néphrotique|112Exanthème infectieux|113Rhumatisme Articulaire Aigue|114Diarrhée aiguë du nourrisson|115CAT devant un état fébrile|116Déshydratation aiguë|117Vaccination - Prévention des maladies infectieuses|118Rachitisme carentiel|119Glomérulonéphrite Aigüe|120Conduite à tenir devant un enfant comateux|121Diagnostic des adénopathies superficielles chez l\'enfant|122Diagnostic des déficits immunitaires de l\'enfant|123Douleurs abdominales chez l\'enfant|129Anomalie de la croissance fœtale|130Les convulsions néonatales|131Le risque périnatal|132Les embryofoetopathies|133Les ictères du nouveau-né|134La prématurité|135Les détresses respiratoires du nouveau-né|136Les infections néonatales|137l allaitement maternel';
			break;
		case'11':
			chaine_chapitres='138Explorations complémentaires en néphrologie|139Classification de glomérulonéphrites chroniques|140La prévention de l’insuffisance rénale chronique|141Les syndromes néphrotiques|142Les néphropathies interstitielles|143La polykystose rénale|144Les insuffisances rénales aigues|145Néphrologie : Les insuffisances rénales chroniques|146Néphrologie : Les glomérulonéphrites aiguës post infectieuses|147Néphrologie : Les glomérulonéphrites chroniques secondaires|148Néphrologie : Les dyskaliémies|149Néphrologie : Les troubles de l’hydratation|150Néphrologie : Rein et HTA h|151Urologie : CAT devant des coliques néphrétiques|152Urologie : CAT devant une hématurie|153Urologie : Cancer du rein|154Urologie : Tumeurs urothéliales|155Urologie : Les traumatismes fermés du rein|156Urologie : Les infections rénales|157Urologie : La tuberculose urogénitale|158Urologie : La lithiase urinaire|159Urologie : L’hypertrophie bénigne de la prostate|160Urologie : Cancer de la prostate|161Urologie : Complications urinaires des fractures du bassin|162Urologie : CAT devant une grosse bourse';
			break;
		case'6':
			chaine_chapitres='163Urologie : L’incontinence urinaire';
			break;
		case'11':
			chaine_chapitres='164Urologie : Le dysfonctionnement érectile – Hypofertilité|165Urologie : Rétrécissement de l\'urètre|166Imagerie de la pathologie du haut appareil urinaire|167Imagerie de la pathologie du bas appareil urinaire|168Rein et médicaments|169Immunologie des glomérulonéphrites|170Immunologie de la transplantation rénale|171Pathologie rénale|172Pathologie vésicale|173Pathologie prostatique|174Pathologie testiculaire|175Diététique de l’insuffisance rénale chronique';
			break;
		case'6':
			chaine_chapitres='176Diététiques des hyper uricémies';
			break;
	}

	return chaine_chapitres;
}